name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build eif-builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: eif-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build EIF image
        run: |
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/output \
            -e DOCKER_IMAGE=hello-world:latest \
            -e EIF_FILE=tinfoil-helper-enclave-${{ github.ref_name }}.eif \
            -e INFO_FILE=tinfoil-helper-enclave-${{ github.ref_name }}-info.json \
            eif-builder:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-path: tinfoil-helper-enclave-${{ github.ref_name }}.eif

      - name: Generate release notes
        id: generate-release-notes
        run: |
          RELEASE_NOTES=$(cat << EOF
          Measurements:
          \`\`\`
          PCR0 $(jq -r ".Measurements.PCR0" tinfoil-helper-enclave-${{ github.ref_name }}-info.json)
          PCR1 $(jq -r ".Measurements.PCR1" tinfoil-helper-enclave-${{ github.ref_name }}-info.json)
          PCR2 $(jq -r ".Measurements.PCR2" tinfoil-helper-enclave-${{ github.ref_name }}-info.json)
          \`\`\`
          Log: https://search.sigstore.dev?logIndex=$(jq -r ".verificationMaterial.tlogEntries[0].logIndex" ${{ steps.attest.outputs.bundle-path }})
          EOF
          )
          echo "release-notes<<EOF" >> "$GITHUB_OUTPUT"
          echo "${RELEASE_NOTES}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tinfoil-helper-enclave-${{ github.ref_name }}.eif
            tinfoil-helper-enclave-${{ github.ref_name }}-info.json
          body: ${{ steps.generate-release-notes.outputs.release-notes }}
